FROM  yasminekd/airflow-sim:latest

RUN pip install pyyaml && pip install pathlib && pip install pandas && pip install minio && pip install setuptools && pip install python-dotenv && pip install psycopg2

